[[main]]
  name = "Curriculum"
  url = "#the-curriculum"
  weight = 1
[[footer]]
  name = "@practicalhugo"
  url = "https://twitter.com/practicalhugo/"
  weight = 1
  [footer.params]
    external = true
[[footer]]
  name = "@harrycresswell"
  url = "https://harrycresswell.com/"
  weight = 2
  [footer.params]
    external = true
[[footer]]
  name = "Changelog"
  url = "/changelog/"
  weight = 3

