# SEO config
keywords = "Hugo course, Go Hugo course, Hugo and Jamastack course, resilient web design, static site generator"
description = "Learn how to build fast, resilient websites with Hugo & the Jamstack."
[twitter]
  handle = "@practicalhugo"
  image = "img/practical-hugo-card.png"
[opengraph]
  image = "img/practical-hugo-card.png"