# SEO config
keywords = "Hugo course, Go Hugo course, Hugo and Jamastack course, resilient web design, static site generator"
description = "Learn how to build simple, resilient websites using Hugo & the Jamstack."