[build]
  command = "npm run build"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.80.0"
  HUGO_ENV = "production"

[[headers]]
  for = "/img/*"
  [headers.values]
  # Cache for 7 days
    Cache-Control = "public, s-max-age=604800"
[[headers]]
  for = "/css/*.css"
  [headers.values]
    # Cache for 7 days
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "js/*.js"
  [headers.values]
    # Cache for 7 days
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "/fonts/*"
  [headers.values]
    # Cache forever
    Cache-Control = "public, max-age=31536000,immutable"